show_author_username:
  type: bool
  default: false
  description:
    en: "Show usernames instead profile avatars in all topic list pages."

show_topic_author_column_first:
  type: bool
  default: false
  description:
    en: "Show topic authors in the first column in all topic list pages."

show_topic_author_column_last:
  type: bool
  default: false
