show_author_in_topic_lists:
  type: bool
  default: false
  description:
    en: "Show the topic author instead of last poster avatar. Leaving disabled will show the last poster avatar."

poster_column_placement:
  type: enum
  default: "Default"
  choices:
    - First
    - Last
    - Default
  description:
    en: "Show topic author or last poster in the first, last or default middle column in all topic list pages."

show_username_instead:
  type: bool
  default: false
  description:
    en: "Show usernames instead of profile avatars in all topic list pages."
