topic_author_or_last_poster:
  type: enum
  default: "Topic Author"
  choices:
    - Topic Author
    - Last Poster
  description:
    en: "Show the topic author or last poster avatar."

avatar_column_placement:
  type: enum
  default: "Default"
  choices:
    - Default
    - First
    - Last
  description:
    en: "Author or poster avatar column placement."

show_username_instead:
  type: bool
  default: false
  description:
    en: "Show usernames instead of avatars in all topic list pages."
