show_author_column_first:
  type: bool
  default: false
  description:
    en: "Show topic authors in the first column in all topic list pages."

show_author_column_last:
  type: bool
  default: false
  description:
    en: "Show topic authors in the last column in all topic list pages. Above setting must be disabled. Leaving both disabled shows default column order."

show_username_instead:
  type: bool
  default: false
  description:
    en: "Show author usernames instead profile avatars in all topic list pages."
